version: '3.9'

services:
  mongodb:
    image: mongo:6-jammy
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    networks:
      - order-network

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - order-network

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672" # interface web do rabbitmq
    networks:
      - order-network

networks:
  order-network:
    driver: bridge