spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/orderdb

    redis:
      host: localhost
      port: 6379

  rabbitmq:
    host: localhost
    username: guest
    password: guest
    listener:
      simple:
        prefetch: 50
        concurrency: 5
        max-concurrency: 20